import { Workout } from "./type";

export const testData: Workout[] = [
  {
    _id:'232323232',
    name: "Bicep Curls",
    muscleGroup: "biceps",
    reps: 13,
    weight: 10,
    date: "14/01/2025"
  },
  // {
  //   name: "Bicep Curls",
  //   muscleGroup: "biceps",
  //   reps: 15,
  //   weight: 10,
  //   date: "15/01/2025",
  // },
  // {
  //   name: "Bicep Curls",
  //   muscleGroup: "biceps",
  //   reps: 8,
  //   weight: 12,
  //   date: "16/01/2025",
  // },
  // {
  //   name: "Bicep Curls",
  //   muscleGroup: "biceps",
  //   reps: 15,
  //   weight: 10,
  //   date: "17/01/2025",
  // },
  // {
  //   name: "Bicep Curls",
  //   muscleGroup: "biceps",
  //   reps: 17,
  //   weight: 12,
  //   date: "18/01/2025",
  // },
  // {
  //   name: "Bicep Curls",
  //   muscleGroup: "biceps",
  //   reps: 18,
  //   weight: 12,
  //   date: "19/01/2025",
  // },
  // {
  //   name: "Preacher Curls",
  //   muscleGroup: "biceps",
  //   reps: 14,
  //   weight: 5,
  //   date: "15/01/2025",
  // },
  // {
  //   name: "Preacher Curls",
  //   muscleGroup: "biceps",
  //   reps: 15,
  //   weight: 5,
  //   date: "16/01/2025",
  // },
  // {
  //   name: "Preacher Curls",
  //   muscleGroup: "biceps",
  //   reps: 8,
  //   weight: 10,
  //   date: "17/01/2025",
  // },
  // {
  //   name: "Preacher Curls",
  //   muscleGroup: "biceps",
  //   reps: 14,
  //   weight: 5,
  //   date: "15/01/2025",
  // },
  // {
  //   name: "Preacher Curls",
  //   muscleGroup: "biceps",
  //   reps: 14,
  //   weight: 5,
  //   date: "15/01/2025",
  // },
  // {
  //   name: "Preacher Curls",
  //   muscleGroup: "biceps",
  //   reps: 14,
  //   weight: 5,
  //   date: "15/01/2025",
  // },
  // {
  //   name: "Preacher Curls",
  //   muscleGroup: "biceps",
  //   reps: 14,
  //   weight: 5,
  //   date: "15/01/2025",
  // },
  // {
  //   name: "Preacher Curls",
  //   muscleGroup: "biceps",
  //   reps: 14,
  //   weight: 5,
  //   date: "15/01/2025",
  // },
  // {
  //   name: "Preacher Curls",
  //   muscleGroup: "biceps",
  //   reps: 14,
  //   weight: 5,
  //   date: "15/01/2025",
  // },
  // {
  //   name: "Preacher Curls",
  //   muscleGroup: "biceps",
  //   reps: 14,
  //   weight: 5,
  //   date: "15/01/2025",
  // },
  // {
  //   name: "Preacher Curls",
  //   muscleGroup: "biceps",
  //   reps: 14,
  //   weight: 5,
  //   date: "15/01/2025",
  // },
  // {
  //   name: "Preacher Curls",
  //   muscleGroup: "biceps",
  //   reps: 14,
  //   weight: 5,
  //   date: "15/01/2025",
  // },
  // {
  //   name: "Preacher Curls",
  //   muscleGroup: "biceps",
  //   reps: 14,
  //   weight: 5,
  //   date: "15/01/2025",
  // },
  // {
  //   name: "Preacher Curls",
  //   muscleGroup: "biceps",
  //   reps: 14,
  //   weight: 5,
  //   date: "15/01/2025",
  // },
];
